### ISSUE TITLE
Report multiple missing unfoldings at the same time

### ISSUE THREAD

**Issue by mgajda** [IntersectMBO/plutus#4283]
### Describe the feature you'd like

Currently Plutus plugin reports only a single missing unfolding.
Big contract will have multiple, so it would be nice to report them as a list instead.

### Describe alternatives you've considered

Alternative is to recompile entire code each time unfolding is captured, which is much longer process and error prone, since Plutus plugin gives no indication of progress, nor location: no line number, nothing.

**Comment by michaelpj** [comment]
> nor location: no line number, nothing

That seems wrong. The plugin should give you errors with locations.

I never figured out a way to make the plugin give errors in the style that the compiler does, but maybe I should give it another try.

>  Big contract will have multiple, so it would be nice to report them as a list instead.

Accumulating errors would be nice, but we'd have to rewrite it to be tolerant of failure instead of just bailing out as soon as it sees a problem.

**Comment by effectfully** [comment]
@mgajda if you're experiencing this problem still, please specify how to reproduce it (I know it's been a long time). It seems this shouldn't be happening, given Michael's response:

> That seems wrong. The plugin should give you errors with locations.

@michaelpj 

> Accumulating errors would be nice, but we'd have to rewrite it to be tolerant of failure instead of just bailing out as soon as it sees a problem.

Sounds like a very useful feature to have, but seems to be considered low priority right now, so I'm adding the label.
