### ISSUE TITLE
Support datatypes mentioning type families

### ISSUE THREAD

**Issue by uhbif19** [IntersectMBO/plutus#5769]
### Describe the feature you'd like

Plutus now supports type families, which is cool. But using datatypes mentioning them fails to compile with `Unsupported feature: Irreducible type family application`. Some (simplified example):

```haskell
class CEMScript script where
    type Params script
    type State script

data CEMScriptDatum = MkCEMScriptDatum {
   params :: Params script,
   state :: State script
}

myScript = 
     ...
     where
         datum :: CEMScriptDatum MyScript
         datum = MkCEMScriptDatum myParams myState
```

Compiling `myScript` would fail, and tracing Plutus shows that compiling of `MkCEMScriptDatum` depends on compiling `CEMScriptDatum MyScript` type, which triggers compiling `Params script` type, which seems wrong to me. Semantically `CEMScriptDatum MyScript` should trigger `Params MyScript` compilation, I believe.

### Describe alternatives you've considered

Using tuple instead of datatype works.

**Comment by zliu41** [comment]
In theory we should be able to compile `CEMScriptDatum MyScript` without compiling `CEMScriptDatum`, but it sounds quite tricky to do and I'm not sure it's worth doing.

**Comment by uhbif19** [comment]
@zliu41 I am not aware why `CEMScriptDatum MyScript` should be compiled, but there is no need to change that. Is see issue with that it depends on `Params script` compilation, not `Params MyScript`, forgetting specific type. Compilation of  `Params MyScript` should work just fine, AFAIU.

**Comment by michaelpj** [comment]
We support type families iff the usages are always completely reducible to non-type-family types. Your datatype is polymorphic over the parameter to the type family, so we can't compile it.

> Compilation of Params MyScript should work just fine, AFAIU.

We don't monomorphise your program for you. You wrote a polymorphic datatype, we compile a polymorphic datatype.

**Comment by uhbif19** [comment]
> You datatype is polymorphic over the parameter to the type family, so we can't compile it.

Why compilation of `CEMScriptDatum MyScript` should be different from type family `Params MyScript`? Is not parametric datatype semantically similar to injective type/data family?

Trace shows that Plutus is already aware of monomorphisation for `CEMScriptDatum` fields, but drops this knoweledge.

**Comment by zliu41** [comment]
> I am not aware why CEMScriptDatum MyScript should be compiled

Because like Michael said, we can't compile `Params script`, we can only compile `Params MyScript` and it is a field of `CEMScriptDatum MyScript`.

**Comment by uhbif19** [comment]
@zliu41 

Could you please point me to part of code handling this, so I could understand it better? So I presume it processes any datatype declaration one by one, but type families are evaluated away into simple datatypes?

Thing is: same code with tuples works. Like `(Params script, State script)` would happily compile. And record in my example is essentially a tuple in disguise. So in terms of representation it seems like it could be handled same way. And it terms of typing, Plutus compiler trace shows that it already knows correct monomorphization of fields.

**Comment by michaelpj** [comment]
> Thing is: same code with tuples works. Like (Params script, State script) would happily compile.

I don't think that will work if we don't know what `script` is, but if we do then we can reduce the type families at the use site and everything is fine.

**Comment by uhbif19** [comment]
@zliu41 

Okay, I kinda get how this works. Compilation works for tuples not cuz of `(,)`  datatype specifically, but generally any parameterized datatype like `data MyTuple a = MkTuple a`, that is something I understood wrong.

Reason is how Plutus normalizes type families. It compiles (with `compileTypeNorm`) type like `TypeApp MyType` by first calling `GHC.normaliseType` on all of it. That way if `TypeApp` is type family it is normalized away. But if `TypeApp` is parameterized datatype, Plutus proceeds by compiling `TypeApp` (with `compileTyCon`) and `MyType` separately (https://github.com/IntersectMBO/plutus/blob/6d5e14ce7457f8317892343dca83fd7619cb7102/plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs#L105). 

`compileTyCon` only gets `TypeApp` as argument, forgetting it applicant, as well as `getDataCons` it is calling. So I draft simple plan of improving it:

1. Push `TypeApp` arguments down to `compileTyCon`.
2. Normalize constructors get from `getDataCons`. I am not sure how to do this correctly. There seem to be field `dcOrigArgTys :: Scaled Type`, which seem to be main target of this. I would research this further.

**Comment by michaelpj** [comment]
I think the thing you're missing is a picture of what this would even look like in PIR. Since we don't support data families there, and we don't have a way to make it into a proper type function, we would need to make monomorphic copies of all the datatypes.

This would be a lot of work, and I'm not sure it would even work, since it would mean that `f :: Foo x -> b` wouldn't be able to accept the monomorphized `FooX`, unless you also monomorphise all the functions that operate on it.

**Comment by effectfully** [comment]
It's quite apparent that there's still confusion around the discussed topic and no way forward is specified, so from what I can tell this issue was not triaged successfully, I'm returning the label therefore.

**Comment by effectfully** [comment]
> Like this works:
>  
> ```
> newtype MyType a = MkMyType a
> value :: MyType (MyFamily Int)
> ```
>  
> But this does not:
>  
> ```
> newtype MyType2 a = MkMyType2 (MyFamily a)
> value2 :: MyType2 Int
> ```
>  
> But encoding of `value` and `value2`, I believe, is exactly the same. 

It's not! Both `value` and `value2` are ill-scoped if they don't have `MkMyType` and `MkMyType2` in the scope, respectively, since the latter have to be used to define the former. And that's where `value` and `value2` differ. `MkMyType` is trivial to define in PIR, `MkMyType2` is not definable in the general case, because type families are not readily representable in PIR. We do have type-level functions in PIR, so we could compile a small subset of closed type families that don't do any pattern matching, but then those are just type synonyms.

It seems like what you want us to do is to somehow pull type families out of data definitions and inline them at each call site, so that GHC can optimize them away before they have a chance to reach PIR. I don't think this is ever going to happen, it would be a ton of effort and additional complexity for such a niche feature, I doubt we'll ever have bandwidth for that.

Summarizing, `MkMyType2` isn't PIR-compatible and we aren't massaging Haskell code in highly non-trivial ways for the sake of PIR-compatibility. I'm therefore closing the issue as "won't do". Do feel free to reopen/comment if there's still confusion / I got something wrong / etc.

**Comment by uhbif19** [comment]
> It's not!

I am pretty sure types representation is isomorphic, just because I refactored code as in example and it works. If they were not isomorphic in representation, it would not work.

> but then those are just type synonyms

In our case they are synonyms indeed. If Plutus does not support type families, it can does not support them in that case as well.

> It seems like what you want us to do is to somehow pull type families out of data definitions and inline them at each call site

I think that in that case the issue is only with type checker, not encoding, and I outlined my proposed solution [here](https://github.com/IntersectMBO/plutus/issues/5769#issuecomment-1959722493). Do you think it wont work? I could try to implement it if debugging custom Plutus plugin is manageable.

**Comment by effectfully** [comment]
> I am pretty sure types representation is isomorphic, just because I refactored code as in example and it works. If they were not isomorphic in representation, it would not work.

`value` and `value2` are isomorphic in the sense that you can convert one to another, but `MyType` and `MyType2` aren't isomorphic before they get applied and their unapplied form is what we would attempt to convert to PIR and fail, because `MyType2` cannot be supported. This is of course unless you transform the code before it reaches PIR, which it seems is what you're after.

> Do you think it wont work?

It looks as if it could allow you to compile data types with type families in them, yes. But that's because it effectively implements monomorphization of _all_ data types, which would be a major misfeature due to script size constraints. We could consider monomorphizing only those types that cannot be compiled otherwise, but I'd argue this would be a questionable feature too for the same reason: implicitly adding a new data type into the scope whenever what looks like an already existing one is referenced by the user is gonna be annoying UX. Maybe we could have explicit monomorphization annotations?

Anyway, your approach is interesting, maybe we could find a use case for some monomorphization, especially if you're gonna try implementing it. I'll reopen the issue and mark it as "low priority" for the time being.

**Comment by effectfully** [comment]
Also, note what Michael said above:

> I'm not sure it would even work, since it would mean that `f :: Foo x -> b` wouldn't be able to accept the monomorphized `FooX`, unless you also monomorphise all the functions that operate on it.

**Comment by uhbif19** [comment]
@effectfully

Surely adding monomorphisation is big change to make and much more complex thing than what I intended to do. But while maybe I am missing something, but I still do not see why it is necessary.

Semantic transformation I see is like desugaring types into parametric polymorphic one, which already covered by Plutus. Like `data C x = MkC (Synonym x)` is runtime-wise same as just `Synonym x`. You can see it by transforming its definition into `data C' x = MkC' x` and all call sites into `C' (Synonym x)`. Representation-wise it is exactly the same, only typing is changed. This transformation should work fine for Michael example, AFAIU. And I do not see why it would not work for more complex cases.

Of course real implementation need not to actually transform code.

**Comment by effectfully** [comment]
> Semantic transformation I see is like desugaring types into parametric polymorphic one, which already covered by Plutus. Like `data C x = MkC (Synonym x)` is runtime-wise same as just `Synonym x`. You can see it by transforming its definition into `data C' x = MkC' x` and all call sites into `C' (Synonym x)`. Representation-wise it is exactly the same, only typing is changed. This transformation should work fine for Michael example, AFAIU. And I do not see why it would not work for more complex cases.

Yes, you can elaborate `C` to `C'` the way you specify, however:

1. that will have horrible UX: the moment `x` isn't a concrete type anywhere in the program the user will get an incomprehensible error message about some code that they didn't write (`C'`). And GHC is likely going to get in the way (because it always does), maybe even create polymorphic definitions with `Synonym` in them, I don't know
2. what if it's `data C x = MkC (Synonym1 x) (Synonym2)`? Now you need to create a new type argument per type family
3. you'll you need to pull those type families transitively: if there's a data type referencing a data type referencing a data type with a type family inside, you'll need to transform all of those

This all sounds like a lot of work for a pretty obscure feature with dubious UX, I'd rather we just say "type families aren't supported, ciao". So given how many much higher priority tasks we have, I don't think we're ever go get to this one, hence I'm closing the issue. If in 10 years we decide that we want this feature, we can always reopen the issue.
