### ISSUE TITLE
Plutus-tx coredumps on XEON v2

### ISSUE THREAD

**Issue by aleksey-makarov** [IntersectMBO/plutus#5842]
### Summary

Plutus-tx executes illegal instructions when it is run on Xeon v2

### Steps to reproduce the behavior

Perform these on 'Intel(R) Xeon(R) CPU E5-2680 v2' machine:
- Initialize nix flake from input-output-hk/iogx haskell template (tried with ghc96 and ghc92)
- Enter development environment with `nix develop`
- Compile simple simple code like this
```
integerOne :: CompiledCode Integer
integerOne = $$(compile [|| (1 :: Integer) ||])
```

### Actual Result

```
Error: cabal: Failed to build hello-1.0.0.2. The build process terminated with exit code -4
```

And when I try to load the code to ghci, it reports

```
Illegal instruction (core dumped)
```

Looking at the coredump I discovered that the instruction was `mulx` from `adx` cpu feature. `/proc/cpuinfo` says that my laptop has that feature, but the server does not.

Except for compiling with `PlutusTx.compile` anything other from `ghc` seems to work on the server well.

### Expected Result

The code compiles as it does on my laptop.

### System info

NixOS
Intel(R) Xeon(R) CPU E5-2680 v2

**Comment by ana-pantilie** [comment]
> Except for compiling with PlutusTx.compile anything other from ghc seems to work on the server well.

Just to make sure, does compiling some Plutus-unrelated Template Haskell code work?

**Comment by kwxm** [comment]
This is probably caused by the [blst library](https://github.com/supranational/blst), which we use to implement some of the cryptographic functions that are used by Plutus Core. By default it uses avx instructions which aren't available on all CPUs, especially older ones. I have no idea why these instructions would be used when compiling unrelated code though (I've seen similar errors myself).  However, the version of `libblst` in our nix environment should now be built with the [__BLST_PORTABLE__](https://github.com/supranational/blst?tab=readme-ov-file#c-static-library) flag set: this enables run-time selection of the instructions that the library uses so that `Illegal instruction` shouldn't happen. Try making sure that the repository is up to data and restart `nix develop` and see if that helps.

**Comment by kwxm** [comment]
Actually I'm not sure if the portable version of `libblst` is in nix yet.  If not, it should be possible to avoid this problem by building the library on your machine (it should be automatically configured to use the right instructions) and pointing to it with `LD_LIBRARY_PATH`.

**Comment by aleksey-makarov** [comment]
> Try making sure that the repository is up to data and restart `nix develop` and see if that helps.

> it should be possible to avoid this problem by building the library on your machine (it should be automatically configured to use the right instructions) and pointing to it with LD_LIBRARY_PATH

Thank you for the reply.  I will do that and will report the results.  Unfortunately, I expect I will have time to do that in about 3-4 days.

**Comment by aleksey-makarov** [comment]
@mmontin, yes thank you
I also testest this with plutus-tx-1.23 and blst library compiled with `-D__BLST_PORTABLE__` and the issue seems to be resolved.
