### ISSUE TITLE
DeserialiseFailureInfo does not account for Flat

### ISSUE THREAD

**Issue by bezirg** [IntersectMBO/plutus#6083]
https://github.com/IntersectMBO/plutus/blob/0114f6d66cf2dd23debe1928a320235a2250b39d/plutus-core/plutus-core/src/Codec/CBOR/Extras.hs#L77-L86

Also we switched to new cborg 2.10 version

**Comment by bezirg** [comment]
I decided to not exactly do what the original issue was about. Instead I added a comment that Flat errors are propagated into `OtherReason` and I refactored related functions I found

**Comment by kwxm** [comment]
[Not directly related to this PR, but it reminded me of something annoying.]

I wonder if we could try to intercept the `flat` errors and try to make them more informative.  We often get questions from people who get errors like
```
Flat deserialisation failure: TooMuchSpace (0x00000042005e82c8,S {currPtr = 0x00000042005e701d, usedBits = 3})
```
and it usually turns out that what's happened is that there's an extra layer of CBOR encoding round a flat-encoded script.  What that error [actually means](https://hackage.haskell.org/package/flat-0.6/docs/src/Flat.Decoder.Run.html#strictDecoder) is that the decoder's got to what it thinks is the end of a buffer and there's still some input left. Maybe it's not helpful to report the full flat error and we should just say "Bad flat encoding" or something. Maybe not though: we cold genuinely have messed something up.

**Comment by bezirg** [comment]
That was my initial plan: intercept Flat errors and propagate/lift them to this DeserialiseFailureInfo. To do that, I would rely to even more string encoding/decoding which I detest
