### ISSUE TITLE
Export from `PlutusLedgerApi.Common`

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/plutus#6098]
### Describe the feature you'd like

This is a very low priority feature request:

Here are some types/classes/functions that are exported from individual plutus version in the `plutus-ledger-api`, but not from Common, despite that they are not tied to an explicit plutus version:

* `ToData(..)`
* `FromData(..)`

(I'll try to see if there are other types/functions/classes that could benefit from being exported from Common and add them to the above list)

**Comment by effectfully** [comment]
> (I'll try to see if there are other types/functions/classes that could benefit from being exported from Common and add them to the above list)

I'm labeling this as `status: needs info from the reporter` then, so once you're done please let us know and we'll fix it all up.

Not labeling this issue as "Low priority", because the simplicity of the fix far outweighs its insignificance, so in my opinion we should just fix the issue and be done with it.

**Comment by lehins** [comment]
> I'm labeling this as status: needs info from the reporter then, so once you're done please let us know and we'll fix it all up.

Perfect! Thank you.

**Comment by lehins** [comment]
I can't find any more functionality at this point that we could export from `Common`.

**Comment by effectfully** [comment]
On it.
