### ISSUE TITLE
Remove immediate unlifting from the spec if possible

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#6118]
Just delete it, so long as we’re able to.

**Comment by kwxm** [comment]
I think we did this a long time ago.  It used to be the case that an ill-typed partial application of a monomorphic builtin (like `[(builtin addInteger) (con string "abc")]`) would fail immediately at runtime but for a polymorphic builtin there wouldn't be an error until it was fully applied (because you couldn't tell if all of the types agreed until you had all of the arguments).  Specifying this behaviour was quite complicated.  This got  fixed in the implementation in #4879 and in the specification in #4960.  The behaviour is now that the arguments of a builtin application don't get converted into Haskell values (with a possible error because something is of the wrong type) until the builtin becomes fully applied. This means that ``[(builtin addInteger) (con string "abc")]`)` is now actually a legal UPLC term which a script can use without error as long as it never gets applied to a second argument.

**Comment by ana-pantilie** [comment]
This was from a pretty old Jira issue, and it had no other details so I had no idea what it's about. Your explanations make sense, thank you @kwxm !
