### ISSUE TITLE
CEK machine to run on open term

### ISSUE THREAD

**Issue by SeungheonOh** [IntersectMBO/plutus#6620]
### Describe the feature you'd like

Currently, CEK can only reduce a closed term. This will allow evaluation of some weak head normal forms into normal forms by iteratively evaluating bodies of lambdas, and few other optimizations powered by reduction of weak head normal forms into normal forms.

**Comment by effectfully** [comment]
I'm not sure about this one. On the one hand, this is a reasonable request. But on the other hand, the CEK machine is the on-chain VM, it's extremely important to keep it as small as possible and as efficient as possible. I've been meaning to drop all the discharging business from it (i.e. make the machine either fail or return an unannotated success, not an evaluated term), because while that stuff is extremely useful for tests, debugging etc, it just doesn't belong to the most important piece of infrastructure we have in Plutus.

Plus, the CEK machine has all that costing overhead. If you just want a normalizer, you can implement some quick HOAS-based one, we've [done](https://github.com/IntersectMBO/plutus/blob/cbabb1da95a0b024cf06e793d88af7b6bb67740a/plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/HOAS.hs) it in the past.

I'll ask the team, but chances are, we'll either close this issue or repurpose it as "provide a HOAS evaluator".

**Comment by SeungheonOh** [comment]
> But on the other hand, the CEK machine is the on-chain VM, it's extremely important to keep it as small as possible and as efficient as possible.

Totally understood. This probably is a good move, keeping more clear distinction between the actual VM and other testing utilities even though they run same UPLC. HOAS-based evaluator would be useful for various stuff. For my interest, that is mainly regarding Plutarch, this would mean we need to change some of the internal representation as we have something quite similar to `HTerm` that gets compiled into raw UPLC except we use tricks from `ST` monad to track free variables at type level. That will be quite big of a change and since HOAS evaluator doesn't look too complicated without all budget calculation stuff, we might just go ahead and write similar evaluator specialized for our implementation.

**Comment by wadler** [comment]
I agree with Roman. Evaluating open terms should be a separate tool.

**Comment by effectfully** [comment]
Great, thank you @SeungheonOh and @wadler for the input, I'm going to close this issue as "won't do" then.
